# --- CONFIGURATION ---
data_root: "./GEVC_CSYNC_PRIMITIVES"
log_dir: "./logs/vibe_gecv"
batch_size: 8          # Faster inference
latent_dim: 512

# Directory containing your .pth files
checkpoint_folder: "./checkpoints/vibe_gecv"
